# Generated by Django 3.0.3 on 2020-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='detail',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Address (if listed in Geodata datasets)', max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(help_text='District', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of Location Visited', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='x_coord',
            field=models.IntegerField(help_text='X-Grid Coordinates'),
        ),
        migrations.AlterField(
            model_name='location',
            name='y_coord',
            field=models.IntegerField(help_text='Y-Grid Coordinates'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.PositiveIntegerField(help_text='Case Number', unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_confirmed',
            field=models.DateField(help_text='Date on which the case was confirmed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(help_text='Identity Document Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='Name of Patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='category',
            field=models.CharField(help_text='Category of the location with respect to patient movements', max_length=50),
        ),
    ]
