# Generated by Django 3.0.3 on 2020-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0003_auto_20200403_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(through='trans19.Visit', to='trans19.Location'),
        ),
    ]
