# Generated by Django 3.0.3 on 2020-04-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0004_patient_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_confirmed']},
        ),
    ]
